drop table RentOutPost;
drop table RentUnit;
drop table RentInRequest;
drop table Notification;
drop table preference;
drop table administer ;
drop table friends;
drop table comment;
drop table image;
drop table post;
drop table account;
